package nft

import (
	"fmt"
	"net/netip"
	"strings"

	"github.com/venth/thn-gateway/internal/netconfig"
)

// Render produces the reviewable command set for a netconfig policy.
//
// # Text only
//
// This function emits iproute2 and nftables commands as text for an operator
// to review. It executes nothing and cannot: the guard would refuse every
// command it prints, which is the mechanism that keeps a rendering bug from
// becoming an execution.
//
// The value is in the review. A gateway change is hard to reverse once
// applied, and reading the exact command list before applying it is the only
// chance to notice that the route points at the wrong interface.
func Render(p netconfig.Policy) string {
	p = p.Clone()
	p.Normalize()

	var b strings.Builder

	writeHeader(&b, p)
	writeForwarding(&b, p)
	writeRoutes(&b, p)
	writeNAT(&b, p)
	writeForwardRules(&b, p)
	writeReminders(&b, p)

	return b.String()
}

// writeHeader emits the preamble.
func writeHeader(b *strings.Builder, p netconfig.Policy) {
	fmt.Fprintf(b, "#!/bin/sh\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# THN data-plane configuration, generated by `thn net render`.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Generated from policy version %d. Do not edit by hand: the next\n", p.Version)
	fmt.Fprintf(b, "# render will overwrite this file.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   %s\n", p)
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# These commands would CHANGE host networking. They are printed for\n")
	fmt.Fprintf(b, "# review only. This build of THN does not execute them.\n")
	fmt.Fprintf(b, "#\n")

	for _, c := range p.Routing.Comments {
		for _, line := range strings.Split(c, "\n") {
			fmt.Fprintf(b, "# %s\n", line)
		}
	}
	if len(p.Routing.Comments) > 0 {
		fmt.Fprintf(b, "#\n")
	}
}

// writeForwarding emits the kernel forwarding switches.
//
// These come first because they gate everything else: with forwarding
// disabled in the kernel, no route and no rule produces any carried traffic,
// and the change looks like it did nothing.
func writeForwarding(b *strings.Builder, p netconfig.Policy) {
	fmt.Fprintf(b, "# --- kernel forwarding -------------------------------------------\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Forwarding must be enabled in the kernel for any of the rules below\n")
	fmt.Fprintf(b, "# to have effect. Without it the kernel drops every forwarded packet\n")
	fmt.Fprintf(b, "# regardless of the routing table or firewall.\n")
	fmt.Fprintf(b, "\n")

	fmt.Fprintf(b, "sysctl -w net.ipv4.ip_forward=%d\n", boolInt(p.Forwarding.IPv4Enabled))
	fmt.Fprintf(b, "sysctl -w net.ipv6.conf.all.forwarding=%d\n", boolInt(p.Forwarding.IPv6Enabled))
	fmt.Fprintf(b, "\n")
}

// writeRoutes emits the routing table.
func writeRoutes(b *strings.Builder, p netconfig.Policy) {
	fmt.Fprintf(b, "# --- routing ----------------------------------------------------\n")
	fmt.Fprintf(b, "#\n")

	if !p.Routing.Enabled {
		fmt.Fprintf(b, "# Routing is disabled: this device is a bridge.\n\n")
		return
	}

	if len(p.Routing.Routes) == 0 && !p.Routing.DefaultGateway.IsValid() {
		fmt.Fprintf(b, "# No static routes are configured. The default route is expected to be\n")
		fmt.Fprintf(b, "# learned from the uplink over DHCP.\n\n")
	}

	table := p.Routing.Table
	if table != "" && table != "main" {
		fmt.Fprintf(b, "# Routing table %q is used; it must exist before these routes are added.\n", table)
		fmt.Fprintf(b, "#   ip route add table %s 0.0.0.0/0 dev lo\n\n", table)
	}

	for _, r := range p.Routing.Routes {
		fmt.Fprintf(b, "# %s\n", routeComment(r))
		fmt.Fprintf(b, "%s\n", routeCommand(r, table))
	}

	if r := defaultRoute(p); r != nil {
		fmt.Fprintf(b, "# Default route. %s\n", defaultComment(p))
		fmt.Fprintf(b, "%s\n", routeCommand(*r, table))
	}

	fmt.Fprintf(b, "\n")
}

// routeCommand renders one route as an iproute2 command.
func routeCommand(r netconfig.Route, table string) string {
	var parts []string
	parts = append(parts, "ip route add")

	if table != "" && table != "main" {
		parts = append(parts, "table", table)
	}

	parts = append(parts, r.Destination.String())

	if r.Interface != "" {
		parts = append(parts, "dev", r.Interface)
	}
	if r.NextHop.IsValid() {
		parts = append(parts, "via", r.NextHop.String())
	}
	if r.Scope != "" {
		parts = append(parts, "scope", r.Scope)
	}
	if r.Source.IsValid() {
		parts = append(parts, "src", r.Source.String())
	}
	if r.Protocol != "" {
		parts = append(parts, "proto", r.Protocol)
	}
	if r.Metric != 0 {
		parts = append(parts, "metric", fmt.Sprintf("%d", r.Metric))
	}

	return strings.Join(parts, " ")
}

// routeComment renders a route's explanation.
func routeComment(r netconfig.Route) string {
	if r.Comment != "" {
		return r.Comment
	}
	return fmt.Sprintf("route to %s via %s", r.Destination,
		ifEmpty(nextHopLabel(r.NextHop), "the next hop"))
}

// defaultRoute builds the default route from the dedicated fields, or nil.
func defaultRoute(p netconfig.Policy) *netconfig.Route {
	if p.Routing.DefaultGatewayInterface == "" && !p.Routing.DefaultGateway.IsValid() {
		return nil
	}

	iface := p.Routing.DefaultGatewayInterface
	if iface == "" {
		iface = p.Interfaces.WAN
	}
	if iface == "" {
		return nil
	}

	return &netconfig.Route{
		Destination: defaultPrefix(p),
		NextHop:     p.Routing.DefaultGateway,
		Interface:   iface,
		Metric:      p.Routing.DefaultMetric,
		Protocol:    "thn",
		Scope:       "global",
	}
}

// defaultComment explains the default route's origin.
func defaultComment(p netconfig.Policy) string {
	if p.Routing.DefaultGateway.IsValid() {
		return fmt.Sprintf("via the configured gateway %s", p.Routing.DefaultGateway)
	}
	return "no gateway address is configured; the uplink supplies one over DHCP"
}

// defaultPrefix returns the default prefix for the policy's address families.
func defaultPrefix(p netconfig.Policy) netip.Prefix {
	if p.Routing.IPv6Enabled && !p.Routing.IPv4Enabled {
		return netip.MustParsePrefix("::/0")
	}
	return netip.MustParsePrefix("0.0.0.0/0")
}

// writeNAT emits address translation.
func writeNAT(b *strings.Builder, p netconfig.Policy) {
	fmt.Fprintf(b, "# --- address translation ------------------------------------------\n")
	fmt.Fprintf(b, "#\n")

	n := p.NAT
	if !n.Enabled {
		fmt.Fprintf(b, "# NAT is disabled. LAN traffic would leave with its original source\n")
		fmt.Fprintf(b, "# address, which most upstream networks will drop.\n\n")
		return
	}

	if n.Comment != "" {
		fmt.Fprintf(b, "# %s\n", n.Comment)
	}

	if n.OutInterface == "" {
		fmt.Fprintf(b, "# NAT has no egress interface, so no translation rule can be written.\n")
		fmt.Fprintf(b, "# An unscoped masquerade rule would rewrite traffic leaving every\n")
		fmt.Fprintf(b, "# interface, including the LAN.\n\n")
		return
	}

	table := "thn_nat"
	cmds := []string{
		fmt.Sprintf("nft add table inet %s", table),
		fmt.Sprintf("nft add chain inet %s postrouting { type nat hook postrouting priority srcnat ; policy accept ; }", table),
	}

	switch n.Mode {
	case netconfig.NATMasquerade:
		cmds = append(cmds,
			fmt.Sprintf("nft add rule inet %s postrouting oifname %q meta l4proto { tcp, udp } masquerade",
				table, n.OutInterface))
		cmds = append(cmds,
			fmt.Sprintf("nft add rule inet %s postrouting oifname %q masquerade",
				table, n.OutInterface))
	case netconfig.NATSNAT:
		if n.SNATAddress.IsValid() {
			cmds = append(cmds,
				fmt.Sprintf("nft add rule inet %s postrouting oifname %q snat to %s",
					table, n.OutInterface, n.SNATAddress))
		}
		if n.SNATPrefix.IsValid() {
			cmds = append(cmds,
				fmt.Sprintf("nft add rule inet %s postrouting oifname %q snat to %s",
					table, n.OutInterface, n.SNATPrefix))
		}
	default:
		fmt.Fprintf(b, "# NAT mode %q translates nothing; no rule is generated.\n\n", n.Mode)
		return
	}

	for _, c := range cmds {
		fmt.Fprintf(b, "%s\n", c)
	}

	// The NAT table lives in its own namespace so that flushing the firewall
	// does not silently remove translation, and vice versa.
	fmt.Fprintf(b, "\n")
	fmt.Fprintf(b, "# NAT lives in a separate table (%q) so that flushing the firewall does\n", table)
	fmt.Fprintf(b, "# not silently remove address translation.\n")
	fmt.Fprintf(b, "\n")
}

// writeForwardRules emits the forwarding decisions as documentation.
//
// Forwarding decisions are normally enforced by the firewall's forward chain
// rather than by iproute2. This section therefore documents what the policy
// says and points at the firewall renderer, rather than emitting commands
// that would duplicate the ruleset and drift from it.
func writeForwardRules(b *strings.Builder, p netconfig.Policy) {
	fmt.Fprintf(b, "# --- forwarding decisions -----------------------------------------\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Forwarding is enforced by the nftables forward chain, not by\n")
	fmt.Fprintf(b, "# iproute2. Generate it with:\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   thn firewall render\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# This policy declares the same decisions, kept here so the two can be\n")
	fmt.Fprintf(b, "# compared. They are documented rather than emitted as commands,\n")
	fmt.Fprintf(b, "# because emitting a second copy would let them drift apart.\n")
	fmt.Fprintf(b, "\n")

	if !p.Forwarding.IPv4Enabled && !p.Forwarding.IPv6Enabled {
		fmt.Fprintf(b, "#   (no forwarding is enabled; every forwarded packet is dropped)\n\n")
		return
	}

	fmt.Fprintf(b, "#   IPv4 forwarding: %t\n", p.Forwarding.IPv4Enabled)
	fmt.Fprintf(b, "#   IPv6 forwarding: %t\n\n", p.Forwarding.IPv6Enabled)

	if p.Forwarding.DropInvalid {
		fmt.Fprintf(b, "#   conntrack-invalid: drop\n")
	}
	if p.Forwarding.AntiSpoofing {
		fmt.Fprintf(b, "#   anti-spoofing:     enabled\n")
	}
	fmt.Fprintf(b, "#\n")

	for _, rule := range p.Forwarding.Rules {
		fmt.Fprintf(b, "#   %-10s %-7s", rule.Direction, rule.Action)
		if len(rule.Source) > 0 {
			fmt.Fprintf(b, " from %s", netconfig.PrefixList(rule.Source))
		}
		if len(rule.Destination) > 0 {
			fmt.Fprintf(b, " to %s", netconfig.PrefixList(rule.Destination))
		}
		fmt.Fprintf(b, "\n")
		if rule.Comment != "" {
			fmt.Fprintf(b, "#     %s\n", rule.Comment)
		}
	}

	fmt.Fprintf(b, "\n")
}

// writeReminders emits closing notes.
func writeReminders(b *strings.Builder, p netconfig.Policy) {
	fmt.Fprintf(b, "# --- before applying ----------------------------------------------\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# These commands change host networking. Applying them from a remote\n")
	fmt.Fprintf(b, "# session can make the device unreachable. Before running them:\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   1. Confirm a recovery path exists and that you can reach the device\n")
	fmt.Fprintf(b, "#      physically if this goes wrong.\n")
	fmt.Fprintf(b, "#   2. Check the admin path survives: `thn net simulate` on a packet from\n")
	fmt.Fprintf(b, "#      your administration network.\n")
	fmt.Fprintf(b, "#   3. Capture the current state so it can be put back:\n")
	fmt.Fprintf(b, "#        ip -j route show > /tmp/routes.json\n")
	fmt.Fprintf(b, "#        nft list ruleset > /tmp/ruleset.nft\n")
	fmt.Fprintf(b, "#        sysctl -a > /tmp/sysctl.txt\n")
	fmt.Fprintf(b, "\n")
	if p.Interfaces.LAN == "" || p.Interfaces.WAN == "" {
		fmt.Fprintf(b, "# NOTE: an interface is not yet identified in this policy, so parts of\n")
		fmt.Fprintf(b, "# the configuration are intentionally absent above. See `thn net validate`.\n")
		fmt.Fprintf(b, "\n")
	}
}

// boolInt renders a bool as the 0 or 1 that sysctl expects.
func boolInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

// ifEmpty returns fallback when s is empty.
func ifEmpty(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}

// nextHopLabel renders a next hop for a comment.
func nextHopLabel(a netip.Addr) string {
	if !a.IsValid() {
		return ""
	}
	return a.String()
}
