package dnsmasq

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"
	"time"

	"github.com/VengeTH/THN-Gateway/internal/dhcp"
	"github.com/VengeTH/THN-Gateway/internal/dns"
)

// Directives emitted by the renderer, in the order they are written.
//
// The order is a behaviour specification. dnsmasq applies directives in file
// order and later directives can override earlier ones for the same option,
// so emitting in a fixed order is what makes the generated file's behaviour
// predictable rather than dependent on how the code happens to be written.
var (
	// globalDirectives configure the process as a whole.
	globalDirectives = []string{
		"port", "no-resolv", "no-hosts", "bind-interfaces",
		"interface", "except-interface", "listen-address",
		"domain-needed", "bogus-priv", "localise-queries", "expand-hosts",
		"domain", "local", "server", "cache-size", "log-queries",
		"dhcp-option", "dhcp-range", "dhcp-host", "dhcp-authoritative",
		"dhcp-leasefile", "dhcp-lease-max", "dhcp-option-force",
		"log-facility", "pid-file", "user", "group", "conf-dir",
		"conf-file", "edns-packet-max", "dns-forward-max",
		"stop-dns-rebind", "rebind-localhost-ok", "rebind-loopback-ok",
		"filter-AAAA", "host-record", "addn-hosts", "hostsdir",
		"dhcp-sequential-ip", "dhcp-hostsfile", "dhcp-ignore",
		"dhcp-name-match", "dhcp-optsfile", "dhcp-script",
		"tag", "set-tag", "log-async", "dhcp-broadcast",
		"dhcp-ignore-names", "dhcp-mac", "dhcp-ipset",
		"no-negcache", "dns-loop-detect", "max-ttl", "min-cache-ttl",
		"query-port", "server=/", "address=/", "cname=",
	}
)

// Render produces a dnsmasq configuration file for a DHCP policy and a DNS
// policy.
//
// Render is a pure function: it writes no file and runs no command. The
// caller decides whether to persist the result.
func Render(dhcpPolicy dhcp.Policy, dnsPolicy dns.Policy, lanPrefix netip.Prefix, gateway netip.Addr) string {
	dnsPolicy.Normalise()

	var b strings.Builder

	writeHeader(&b, dhcpPolicy, dnsPolicy)
	writeListeners(&b, dhcpPolicy, dnsPolicy)
	writeDNS(&b, dnsPolicy)
	writeDHCP(&b, dhcpPolicy, lanPrefix, gateway)
	writeNotes(&b)

	return b.String()
}

// writeHeader emits the preamble.
func writeHeader(b *strings.Builder, dp dhcp.Policy, np dns.Policy) {
	fmt.Fprintf(b, "# dnsmasq configuration generated by `thn dhcp render`.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# DO NOT EDIT BY HAND. The next render overwrites this file.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   dhcp: %s\n", dp)
	fmt.Fprintf(b, "#   dns:  %s\n", np)
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# THN does not start or reload dnsmasq. After reviewing this file:\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   dnsmasq --test --conf-file=%s\n", dp.Backend.ConfigFile)
	fmt.Fprintf(b, "#   systemctl reload dnsmasq\n")
	fmt.Fprintf(b, "#\n")

	for _, c := range dp.Comments {
		for _, line := range strings.Split(c, "\n") {
			fmt.Fprintf(b, "# %s\n", line)
		}
	}
	if len(dp.Comments) > 0 {
		fmt.Fprintf(b, "#\n")
	}
}

func writeListeners(b *strings.Builder, p dhcp.Policy, np dns.Policy) {
	fmt.Fprintf(b, "# --- listeners ---------------------------------------------------\n")
	fmt.Fprintf(b, "#\n")

	// The interface list is the union of both roles, because dnsmasq is one
	// process serving both and would otherwise listen on the wrong set.
	iface := p.Interface
	if iface == "" {
		iface = np.Interface
	}

	if iface != "" {
		// Listening only on the LAN is what keeps a DHCP server off the WAN.
		// A dnsmasq that listens on the uplink will answer DHCP offers to
		// anyone on the internet who sends a broadcast.
		fmt.Fprintf(b, "interface=%s\n", iface)
		fmt.Fprintf(b, "bind-interfaces\n")
		fmt.Fprintf(b, "\n")
	} else {
		fmt.Fprintf(b, "# No interface is configured. dnsmasq would listen on every\n")
		fmt.Fprintf(b, "# interface including the WAN, which exposes the DHCP server.\n")
		fmt.Fprintf(b, "\n")
	}

	// dnsmasq refuses to start as root without these.
	fmt.Fprintf(b, "user=root\n")
	fmt.Fprintf(b, "group=root\n")
	fmt.Fprintf(b, "\n")

	if p.Backend.LeaseFile != "" {
		fmt.Fprintf(b, "dhcp-leasefile=%s\n", p.Backend.LeaseFile)
	}
	if p.LeaseMax > 0 {
		fmt.Fprintf(b, "dhcp-lease-max=%d\n", p.LeaseMax)
	}
	fmt.Fprintf(b, "\n")
}

// writeDNS emits the name resolution directives.
func writeDNS(b *strings.Builder, p dns.Policy) {
	fmt.Fprintf(b, "# --- DNS ---------------------------------------------------------\n")
	fmt.Fprintf(b, "#\n")

	if !p.Enabled {
		// port=0 disables the DNS server while leaving DHCP running, which is
		// how dnsmasq serves one role without the other.
		fmt.Fprintf(b, "# DNS is disabled. port=0 turns off name resolution while leaving\n")
		fmt.Fprintf(b, "# DHCP serving.\n")
		fmt.Fprintf(b, "port=0\n\n")
		return
	}

	if p.ListenAddress.IsValid() {
		fmt.Fprintf(b, "listen-address=%s\n", p.ListenAddress)
		fmt.Fprintf(b, "\n")
	}

	if len(p.Upstream) == 0 {
		fmt.Fprintf(b, "# No upstream resolvers are configured. Only locally served names\n")
		fmt.Fprintf(b, "# would resolve; everything else would fail.\n")
		fmt.Fprintf(b, "#\n")
		fmt.Fprintf(b, "# Using the host's own resolvers is not implied: with no-resolv and\n")
		fmt.Fprintf(b, "# no server directive, dnsmasq answers nothing for external names.\n")
	} else {
		// no-resolv stops dnsmasq reading /etc/resolv.conf. Without it the
		// upstream list below would be combined with the host's, and a
		// misconfigured resolv.conf would silently redirect every query.
		fmt.Fprintf(b, "# Queries are forwarded only to the resolvers below, not to whatever\n")
		fmt.Fprintf(b, "# /etc/resolv.conf happens to contain.\n")
		fmt.Fprintf(b, "no-resolv\n")
		fmt.Fprintf(b, "no-hosts\n")
		for _, u := range p.Upstream {
			fmt.Fprintf(b, "server=%s\n", u)
		}
	}

	if p.CacheSize > 0 {
		fmt.Fprintf(b, "cache-size=%d\n", p.CacheSize)
	}

	if p.RejectUnmappedBlocks {
		// Answering a forward query with a private address for a public name
		// is what turns a resolver into a DNS rebinding vector against the
		// browser or service that trusts it.
		fmt.Fprintf(b, "stop-dns-rebind\n")
		fmt.Fprintf(b, "rebind-localhost-ok\n")
		fmt.Fprintf(b, "rebind-loopback-ok\n")
	}

	if p.NoIPv6 {
		// Answering AAAA with nothing is what makes clients fall back to
		// IPv4 immediately rather than following a path that fails slowly.
		fmt.Fprintf(b, "filter-AAAA\n")
	}

	if p.LogQueries {
		fmt.Fprintf(b, "# Query logging is enabled. This writes to disk continuously; on a busy\n")
		fmt.Fprintf(b, "# network it is the fastest way to fill a small filesystem.\n")
		fmt.Fprintf(b, "log-queries\n")
	}

	if p.LocalDomain != "" {
		fmt.Fprintf(b, "\n")
		fmt.Fprintf(b, "# Local domain %q. Names in it are answered here and never\n", p.LocalDomain)
		fmt.Fprintf(b, "# forwarded, so a client asking for a local name cannot be\n")
		fmt.Fprintf(b, "# redirected outward by a hostile upstream.\n")
		fmt.Fprintf(b, "local=/%s/\n", p.LocalDomain)
		fmt.Fprintf(b, "domain=%s\n", p.LocalDomain)
		fmt.Fprintf(b, "expand-hosts\n")
		fmt.Fprintf(b, "domain-needed\n")
		fmt.Fprintf(b, "bogus-priv\n")
	}

	if len(p.LocalRecords) > 0 {
		fmt.Fprintf(b, "\n")
		fmt.Fprintf(b, "# Local records\n")
		fmt.Fprintf(b, "#\n")
		fmt.Fprintf(b, "# dnsmasq has no A-record directive. A local name is expressed with\n")
		fmt.Fprintf(b, "# host-record, which takes an address and a domain per argument.\n")
		for _, rec := range p.LocalRecords {
			line := hostRecordDirective(rec, p.LocalDomain)
			if line == "" {
				continue
			}
			fmt.Fprintf(b, "%s\n", line)
		}
	}

	fmt.Fprintf(b, "\n")
}

// hostRecordDirective renders one local record as a host-record line.
//
// A hosts-file style line would be a syntax error here: dnsmasq's config file
// contains only directives, and a bare "address name" line is not one. The
// host-record form is the supported way to serve a local name.
func hostRecordDirective(rec dns.Record, domain string) string {
	if !rec.Address.IsValid() || rec.Hostname == "" {
		return ""
	}

	names := append([]string{rec.Hostname}, rec.Aliases...)
	seen := map[string]bool{}
	qualified := make([]string, 0, len(names))

	for _, n := range names {
		if n == "" {
			continue
		}
		fqdn := qualify(n, domain)
		if seen[fqdn] {
			continue
		}
		seen[fqdn] = true
		qualified = append(qualified, fqdn)
	}

	if len(qualified) == 0 {
		return ""
	}

	return fmt.Sprintf("host-record=%s,%s",
		rec.Address.String(), strings.Join(qualified, ","))
}

// qualify appends the local domain to a name that lacks it.
func qualify(name, domain string) string {
	if domain == "" {
		return name
	}
	if strings.HasSuffix(name, ".") {
		return name + domain
	}
	return name + "." + domain
}

// writeDHCP emits the address assignment directives.
func writeDHCP(b *strings.Builder, p dhcp.Policy, lanPrefix netip.Prefix, gateway netip.Addr) {
	fmt.Fprintf(b, "# --- DHCP ---------------------------------------------------------\n")
	fmt.Fprintf(b, "#\n")

	if !p.Enabled {
		fmt.Fprintf(b, "# DHCP is disabled. No addresses will be served on the LAN.\n\n")
		return
	}

	if len(p.Ranges) == 0 {
		fmt.Fprintf(b, "# No pools are configured. No addresses will be served.\n\n")
	} else {
		netmask := netmaskFor(lanPrefix, p.Ranges[0].Netmask)

		for _, rg := range p.Ranges {
			fmt.Fprintf(b, "# Pool %s\n", rg.String())
			fmt.Fprintf(b, "dhcp-range=%s,%s,%s,%s\n",
				rg.Start, rg.End, netmask, durationValue(p.LeaseTime))
		}

		// The router option is what makes a client able to reach anything.
		// Without it a client configures successfully, obtains an address,
		// and then cannot route — a failure that looks like a network fault
		// rather than a missing option.
		if gateway.IsValid() {
			fmt.Fprintf(b, "# The router option. Without it clients obtain an address but\n")
			fmt.Fprintf(b, "# cannot reach anything beyond the LAN.\n")
			fmt.Fprintf(b, "dhcp-option=option:router,%s\n", gateway)
		} else {
			fmt.Fprintf(b, "# The gateway address is unknown, so no router option is emitted.\n")
			fmt.Fprintf(b, "# Clients would obtain an address and be unable to route.\n")
		}

		// Point clients at this host for DNS when it is serving. Advertising
		// an external resolver instead would bypass this gateway's own DNS
		// policy, and with it the visibility the DNS layer is for.
		if p.GatewayAddress.IsValid() {
			fmt.Fprintf(b, "# Clients are pointed at this host for DNS.\n")
			fmt.Fprintf(b, "dhcp-option=option:dns-server,%s\n", p.GatewayAddress)
		}

		if p.Domain != "" {
			fmt.Fprintf(b, "dhcp-option=option:domain-search,%s\n", p.Domain)
		}

		fmt.Fprintf(b, "\n")
	}

	if p.Authoritative {
		fmt.Fprintf(b, "# Declaring authority prevents a client that cannot reach this\n")
		fmt.Fprintf(b, "# server from obtaining an address from the upstream network, which\n")
		fmt.Fprintf(b, "# would place it outside this gateway entirely.\n")
		fmt.Fprintf(b, "dhcp-authoritative\n\n")
	}

	if len(p.Reservations) > 0 {
		fmt.Fprintf(b, "# Reservations\n")
		fmt.Fprintf(b, "#\n")
		for _, res := range p.Reservations {
			fmt.Fprintf(b, "%s\n", reservationDirective(res))
		}
		fmt.Fprintf(b, "\n")
	}
}

// reservationDirective renders one dhcp-host line.
//
// A reserved address is rendered as 0.0.0.0 when unspecified, which is
// dnsmasq's way of saying "any address from the pool" while still pinning the
// device to a consistent one.
func reservationDirective(res dhcp.Reservation) string {
	addr := "0.0.0.0"
	if res.Address.IsValid() {
		addr = res.Address.String()
	}

	parts := []string{
		"dhcp-host=" + dhcp.NormalisedMAC(res.MAC),
		"set:" + clientIDFor(res.MAC),
		addr,
	}
	if res.Hostname != "" {
		parts = append(parts, res.Hostname)
	}
	if res.LeaseTime > 0 {
		parts = append(parts, durationValue(res.LeaseTime))
	}

	return strings.Join(parts, ",")
}

// clientIDFor derives a stable client identifier from a MAC.
//
// dnsmasq's "set:" form tells the server to generate a persistent client id
// from the hardware address. Without it a client that sends a different id on
// each request appears as a new device on every renewal, which fills the lease
// table with duplicates of the same hardware.
func clientIDFor(mac string) string {
	return dhcp.NormalisedMAC(mac)
}

// netmaskFor determines the netmask for a pool, preferring an explicit
// override, then the LAN prefix, then the classful default for the address.
func netmaskFor(prefix netip.Prefix, override netip.Addr) string {
	if override.IsValid() {
		return override.String()
	}
	if prefix.IsValid() {
		return netmaskFromBits(prefix.Bits(), prefix.Addr().Is4()).String()
	}
	return "255.255.255.0"
}

// netmaskFromBits returns the netmask for a prefix length.
func netmaskFromBits(bits int, is4 bool) netip.Addr {
	if !is4 {
		return netip.Addr{}
	}
	if bits < 0 || bits > 32 {
		bits = 24
	}
	v := uint32(0xFFFFFFFF) << uint(32-bits)
	return netip.AddrFrom4([4]byte{byte(v >> 24), byte(v >> 16), byte(v >> 8), byte(v)})
}

// durationValue renders a duration in dnsmasq's format, which accepts a bare
// number of seconds or a suffixed value.
func durationValue(d time.Duration) string {
	if d <= 0 {
		return "infinite"
	}
	if d%time.Hour == 0 {
		return fmt.Sprintf("%dh", int(d.Hours()))
	}
	if d%time.Minute == 0 {
		return fmt.Sprintf("%dm", int(d.Minutes()))
	}
	return fmt.Sprintf("%ds", int(d.Seconds()))
}

// writeNotes emits the closing reminders.
func writeNotes(b *strings.Builder) {
	fmt.Fprintf(b, "# --- notes -------------------------------------------------------\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# This file was generated, not applied. Nothing has changed.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Before loading it, capture what is currently in place:\n")
	fmt.Fprintf(b, "#   nft list ruleset > /tmp/before.nft\n")
	fmt.Fprintf(b, "#   cp /etc/dnsmasq.conf /tmp/dnsmasq.conf.before\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# dnsmasq will refuse to serve DHCP on an interface that is not\n")
	fmt.Fprintf(b, "# present, so a generated file for unidentified hardware fails to\n")
	fmt.Fprintf(b, "# start rather than half-working.\n")
	fmt.Fprintf(b, "\n")
}

// KnownDirective reports whether name is a dnsmasq directive this build emits
// or understands.
//
// The rendered configuration is only as good as the directive names in it: a
// typo produces a file dnsmasq accepts and ignores, which is how a gateway
// ends up with no DNS and no indication why. The check exists so a rendered
// file can be verified without loading it.
func KnownDirective(name string) bool {
	for _, d := range globalDirectives {
		if d == name {
			return true
		}
	}
	return false
}

// DirectiveIssue describes a problem in a rendered configuration line.
type DirectiveIssue struct {
	// Line is the one-based line number.
	Line int `json:"line"`
	// Directive is the directive name that was not recognised.
	Directive string `json:"directive"`
	// Message describes the problem.
	Message string `json:"message"`
}

// ValidateConfig checks a rendered dnsmasq configuration.
//
// It does not parse the file the way dnsmasq does. It checks the property
// that matters and is cheap to check: that every directive is one dnsmasq
// actually understands. A file containing only known directives that dnsmasq
// still rejects is a far smaller risk than one containing a typo that is
// silently ignored.
func ValidateConfig(content string) []DirectiveIssue {
	var issues []DirectiveIssue

	for i, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		name, _, _ := strings.Cut(trimmed, "=")
		name = strings.TrimSpace(name)

		if !KnownDirective(name) {
			issues = append(issues, DirectiveIssue{
				Line:      i + 1,
				Directive: name,
				Message: fmt.Sprintf(
					"%q is not a dnsmasq directive this build knows; dnsmasq would ignore it silently",
					name),
			})
		}
	}

	return issues
}

// RenderReservations renders only the reservation lines, for review without
// the rest of the file.
func RenderReservations(p dhcp.Policy) []string {
	res := make([]dhcp.Reservation, len(p.Reservations))
	copy(res, p.Reservations)
	sort.SliceStable(res, func(i, j int) bool {
		return dhcp.NormalisedMAC(res[i].MAC) < dhcp.NormalisedMAC(res[j].MAC)
	})

	out := make([]string, 0, len(res))
	for _, r := range res {
		out = append(out, reservationDirective(r))
	}
	return out
}
