// Package network_test exercises the host-inspection parsers against recorded
// `ip -j` output.
//
// # Why these fixtures are checked in rather than generated
//
// The parsers turn iproute2's JSON into THN's view of a gateway. They have
// never executed: `internal/network/platform_other.go` sets `supported = false`
// off Linux, so on any development machine every call short-circuits before
// reaching them.
//
// That means the shape of this JSON was written from documentation and memory,
// and a mistake in it would surface for the first time on an unattended device
// that nobody can reach. That is the worst possible place to find out.
//
// So the fixtures are literal captures of `ip -j` output, one per subsystem.
// They are not generated by a helper, because a helper would agree with the
// parser by construction and would prove nothing. When `ip` changes its output
// shape, a test here fails and a human decides whether the parser or the
// expectation is wrong — which is the decision that matters and the one a
// generated fixture silently makes for you.
//
// # What each test asserts
//
// The parsed values, not merely that parsing succeeds. A parser that returns an
// empty list without error is the failure mode that matters most here: THN
// would report a gateway as having no interfaces, which is indistinguishable
// from a gateway with no network card, and both look like a healthy host with
// nothing wrong with it.

package network_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/VengeTH/THN-Gateway/internal/network"
)

// fixture reads a checked-in capture.
func fixture(t *testing.T, name string) []byte {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("reading fixture %s: %v", name, err)
	}
	return raw
}

// ------------------------------------------------------------------- links

func TestParseLinksReadsARealGateway(t *testing.T) {
	ifaces, err := network.ParseLinks(fixture(t, "link.json"))
	if err != nil {
		t.Fatalf("ParseLinks: %v", err)
	}
	if len(ifaces) == 0 {
		t.Fatal("ParseLinks returned nothing; an empty list is indistinguishable from a host with no interfaces")
	}

	wan := find(ifaces, "enp0s31f6")
	if wan == nil {
		t.Fatalf("the uplink was not found; got %v", names(ifaces))
	}
	if wan.MAC != "e4:90:69:3a:1c:2f" {
		t.Errorf("uplink MAC = %q, want e4:90:69:3a:1c:2f", wan.MAC)
	}
	if wan.MTU != 1500 {
		t.Errorf("uplink MTU = %d, want 1500", wan.MTU)
	}
	if wan.State != network.LinkUp {
		t.Errorf("uplink state = %s, want UP", wan.State)
	}
	if wan.Index != 2 {
		t.Errorf("uplink index = %d, want 2", wan.Index)
	}
}

// The loopback must come back as a loopback and up, because dnsmasq binds to it
// and a missing `lo` breaks name resolution in a way that looks like a DNS bug.
func TestParseLinksHandlesLoopback(t *testing.T) {
	ifaces, err := network.ParseLinks(fixture(t, "link.json"))
	if err != nil {
		t.Fatal(err)
	}

	lo := find(ifaces, "lo")
	if lo == nil {
		t.Fatal("the loopback interface is missing")
	}
	if lo.State != network.LinkUp {
		t.Errorf("loopback state = %s, want UP", lo.State)
	}
	if lo.Kind != "loopback" {
		t.Errorf("loopback kind = %q, want loopback", lo.Kind)
	}
}

// An absent carrier is DOWN, not UNKNOWN. The difference is whether a rule can
// distinguish "the link is down" from "I could not read the link".
func TestParseLinksDistinguishesDownFromUnknown(t *testing.T) {
	down := []byte(`[{"ifname":"eth9","ifindex":9,"mtu":1500,
		"operstate":"DOWN","address":"aa:bb:cc:dd:ee:ff","flags":["BROADCAST","MULTICAST"]}]`)

	ifaces, err := network.ParseLinks(down)
	if err != nil {
		t.Fatal(err)
	}
	if len(ifaces) != 1 {
		t.Fatalf("got %d interfaces, want 1", len(ifaces))
	}
	if ifaces[0].State != network.LinkDown {
		t.Errorf("operstate DOWN gave %s, want DOWN", ifaces[0].State)
	}

	// An operstate the kernel reports that THN does not know must be UNKNOWN,
	// not silently treated as up.
	odd := []byte(`[{"ifname":"eth9","ifindex":9,"mtu":1500,"operstate":"WEIRD"}]`)
	unknown, err := network.ParseLinks(odd)
	if err != nil {
		t.Fatal(err)
	}
	if unknown[0].State != network.LinkUnknown {
		t.Errorf("an unrecognised operstate gave %s, want UNKNOWN", unknown[0].State)
	}
}

// A container's veth is not a WAN and a bond is not a LAN. The kind is what
// lets a later stage tell them apart.
func TestParseLinksReadsLinkKinds(t *testing.T) {
	ifaces, err := network.ParseLinks(fixture(t, "link.json"))
	if err != nil {
		t.Fatal(err)
	}

	bond := find(ifaces, "bond0")
	if bond == nil {
		t.Fatalf("the bond was not found; got %v", names(ifaces))
	}
	if bond.Kind != "bond" {
		t.Errorf("bond kind = %q, want bond", bond.Kind)
	}

	veth := find(ifaces, "veth1234@if5")
	if veth == nil {
		t.Fatalf("the veth was not found; got %v", names(ifaces))
	}
	if veth.Kind != "veth" {
		t.Errorf("veth kind = %q, want veth", veth.Kind)
	}
}

func TestParseLinksRejectsMalformedInput(t *testing.T) {
	if _, err := network.ParseLinks([]byte(`not json`)); err == nil {
		t.Fatal("malformed input was accepted")
	}
}

// An empty array is valid and means no interfaces. It is not an error, and
// conflating the two would turn an empty container into a broken host.
func TestParseLinksAcceptsAnEmptyList(t *testing.T) {
	ifaces, err := network.ParseLinks([]byte(`[]`))
	if err != nil {
		t.Fatalf("an empty array was rejected: %v", err)
	}
	if len(ifaces) != 0 {
		t.Errorf("got %d interfaces from an empty array", len(ifaces))
	}
}

// ---------------------------------------------------------------- addresses

func TestParseAddressesReadsBothFamilies(t *testing.T) {
	addrs, err := network.ParseAddresses(fixture(t, "addr.json"))
	if err != nil {
		t.Fatalf("ParseAddresses: %v", err)
	}
	if len(addrs) == 0 {
		t.Fatal("ParseAddresses returned nothing")
	}

	v4 := findAddr(addrs, "10.77.0.1/24")
	if v4 == nil {
		t.Fatalf("the LAN address was not found; got %v", cidrs(addrs))
	}
	if v4.Interface != "bond0" {
		t.Errorf("LAN address is on %q, want bond0", v4.Interface)
	}
	if v4.Family != "inet" {
		t.Errorf("family = %q, want inet", v4.Family)
	}

	v6 := findAddr(addrs, "2001:db8:1::50/64")
	if v6 == nil {
		t.Fatalf("the uplink IPv6 address was not found; got %v", cidrs(addrs))
	}
	if v6.Interface != "enp0s31f6" {
		t.Errorf("the uplink IPv6 address is on %q, want enp0s31f6", v6.Interface)
	}
	if v6.Family != "inet6" {
		t.Errorf("family = %q, want inet6", v6.Family)
	}
}

// `ip -j addr` also reports link-local and other families THN does not model.
// Including them would put addresses in the snapshot that no configured
// network contains, and every diff would report them as drift.
func TestParseAddressesIgnoresNonIPFamilies(t *testing.T) {
	addrs, err := network.ParseAddresses(fixture(t, "addr.json"))
	if err != nil {
		t.Fatal(err)
	}
	for _, a := range addrs {
		if a.Family != "inet" && a.Family != "inet6" {
			t.Errorf("a %s address was kept: %s", a.Family, a.CIDR)
		}
		if strings.Contains(a.CIDR, "link/") {
			t.Errorf("a link-layer entry was kept as an address: %s", a.CIDR)
		}
	}
}

// The prefix length has to survive, because a /24 and a /16 on the same address
// are different networks and overlapping them is a routing outage.
func TestParseAddressesPreservesThePrefixLength(t *testing.T) {
	addrs, err := network.ParseAddresses(fixture(t, "addr.json"))
	if err != nil {
		t.Fatal(err)
	}
	for _, a := range addrs {
		if !strings.Contains(a.CIDR, "/") {
			t.Errorf("address %q lost its prefix length", a.CIDR)
		}
	}
}

// ------------------------------------------------------------------- routes

func TestParseRoutesFindsTheDefaultRoute(t *testing.T) {
	routes, err := network.ParseRoutes(fixture(t, "route.json"))
	if err != nil {
		t.Fatalf("ParseRoutes: %v", err)
	}
	if len(routes) == 0 {
		t.Fatal("ParseRoutes returned nothing")
	}

	def := defaultRoute(routes)
	if def == nil {
		t.Fatalf("no default route was found in %v", dests(routes))
	}
	if def.Gateway != "192.168.1.1" {
		t.Errorf("default gateway = %q, want 192.168.1.1", def.Gateway)
	}
	if def.Interface != "enp0s31f6" {
		t.Errorf("default route interface = %q, want enp0s31f6", def.Interface)
	}
	if !def.Default {
		t.Error("the default route is not marked as default")
	}
}

// `ip -j route` reports the default route as `"dst": "default"` on some
// versions and omits `dst` entirely on others. Both are the default route, and a
// gateway that treated them as two different routes would have a default route
// it did not know it had.
func TestParseRoutesNormalisesBothDefaultRouteForms(t *testing.T) {
	for _, raw := range []string{
		`[{"dst":"default","gateway":"192.168.1.1","dev":"enp0s31f6","metric":100}]`,
		`[{"gateway":"192.168.1.1","dev":"enp0s31f6","metric":100}]`,
	} {
		routes, err := network.ParseRoutes([]byte(raw))
		if err != nil {
			t.Fatalf("ParseRoutes(%s): %v", raw, err)
		}
		if len(routes) != 1 {
			t.Fatalf("got %d routes, want 1", len(routes))
		}
		if !routes[0].Default || routes[0].Destination != "default" {
			t.Errorf("%s was not recognised as the default route: %+v", raw, routes[0])
		}
	}
}

// The default route has to sort first: a gateway that picked a more specific
// route to describe its egress would describe the wrong path.
func TestParseRoutesSortsTheDefaultFirst(t *testing.T) {
	routes, err := network.ParseRoutes(fixture(t, "route.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !routes[0].Default {
		t.Errorf("the first route is %q, want the default route", routes[0].Destination)
	}
}

// The metric has to survive: two routes to the same prefix are distinguished
// only by metric, and losing it makes them look like a duplicate.
func TestParseRoutesKeepsMetrics(t *testing.T) {
	routes, err := network.ParseRoutes(fixture(t, "route.json"))
	if err != nil {
		t.Fatal(err)
	}

	def := defaultRoute(routes)
	if def == nil {
		t.Fatal("no default route")
	}
	if def.Metric != 100 {
		t.Errorf("default metric = %d, want 100", def.Metric)
	}
}

// --------------------------------------------------------------- neighbours

func TestParseNeighboursReadsTheArpTable(t *testing.T) {
	n, err := network.ParseNeighbours(fixture(t, "neigh.json"))
	if err != nil {
		t.Fatalf("ParseNeighbours: %v", err)
	}
	if len(n) == 0 {
		t.Fatal("ParseNeighbours returned nothing")
	}

	var found bool
	for _, e := range n {
		if e.Address == "10.77.0.50" {
			found = true
			if e.LinkLayer != "aa:bb:cc:dd:ee:01" {
				t.Errorf("link-layer = %q", e.LinkLayer)
			}
			if !strings.Contains(e.State, "REACHABLE") {
				t.Errorf("state = %q, want it to include REACHABLE", e.State)
			}
		}
	}
	if !found {
		t.Errorf("the known host was not found in %+v", n)
	}
}

// An entry that failed to resolve has no link-layer address. It is still worth
// reporting: "I tried and it did not answer" is different from "there is
// nothing there".
func TestParseNeighboursKeepsFailedEntries(t *testing.T) {
	n, err := network.ParseNeighbours(fixture(t, "neigh.json"))
	if err != nil {
		t.Fatal(err)
	}

	var failed bool
	for _, e := range n {
		if strings.Contains(e.State, "FAILED") {
			failed = true
		}
	}
	if !failed {
		t.Errorf("a failed neighbour was dropped: %+v", n)
	}
}

func TestParseNeighboursAcceptsAnEmptyTable(t *testing.T) {
	n, err := network.ParseNeighbours([]byte(`[]`))
	if err != nil {
		t.Fatalf("an empty table was rejected: %v", err)
	}
	if len(n) != 0 {
		t.Errorf("got %d neighbours from an empty table", len(n))
	}
}

// ------------------------------------------------------------------ helpers

func find(is []network.Interface, name string) *network.Interface {
	for i := range is {
		if is[i].Name == name {
			return &is[i]
		}
	}
	return nil
}

func names(is []network.Interface) []string {
	out := make([]string, 0, len(is))
	for _, i := range is {
		out = append(out, i.Name)
	}
	return out
}

func findAddr(as []network.Address, cidr string) *network.Address {
	for i := range as {
		if as[i].CIDR == cidr {
			return &as[i]
		}
	}
	return nil
}

func cidrs(as []network.Address) []string {
	out := make([]string, 0, len(as))
	for _, a := range as {
		out = append(out, a.CIDR)
	}
	return out
}

func defaultRoute(rs []network.Route) *network.Route {
	for i := range rs {
		if rs[i].Default {
			return &rs[i]
		}
	}
	return nil
}

func dests(rs []network.Route) []string {
	out := make([]string, 0, len(rs))
	for _, r := range rs {
		out = append(out, r.Destination)
	}
	return out
}
