package nft

import (
	"fmt"
	"sort"
	"strings"

	"github.com/VengeTH/THN-Gateway/internal/firewall/policy"
)

// Render turns a policy into an nftables ruleset.
//
// # This produces text and nothing else
//
// Render is a pure function. It reads no host state, executes no command, and
// writes no file. The output is meant to be read, diffed and reviewed before
// anyone types `nft -f`. That separation is what makes `thn firewall render`
// safe to run against an unattended device: it cannot install anything even
// if the caller has root, because it never invokes nft.
//
// # Ordering
//
// Netfilter evaluates rules in order and stops at the first match, so the
// order below is a behaviour specification rather than a formatting choice:
//
//	input     established, then loopback, then ICMP, then services, then the
//	          default policy. Administrative access must come before the
//	          default drop, or it is unreachable.
//	forward   established, then anti-spoof, then the permitted directions,
//	          then the default policy.
//	post      masquerade, which must follow the forward decision because it
//	          only applies to traffic that is actually being forwarded.
//
// # Comments
//
// Every rule carries a comment. A ruleset is a security boundary that someone
// has to audit under pressure at three in the morning; a comment explaining
// why a rule exists is the difference between a five-minute review and a
// two-hour archaeology exercise.
func Render(p policy.Policy) string {
	p = p.Clone()
	p.Normalize()

	var b strings.Builder

	writeHeader(&b, p)
	writeTable(&b, p)
	writeInputChain(&b, p)
	writeForwardChain(&b, p)
	writeNatChain(&b, p)
	writePostrouting(&b, p)
	writeLogging(&b, p)

	// Close the table. Every writer above opens a chain inside it, so the
	// table brace opened in writeTable is closed last. Omitting this produces
	// a ruleset that fails to parse, which means the firewall was never
	// installed at all.
	b.WriteString("}\n")

	return b.String()
}

// writeHeader emits the file preamble.
func writeHeader(b *strings.Builder, p policy.Policy) {
	fmt.Fprintf(b, "#!/usr/sbin/nft -f\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# THN gateway firewall, generated by `thn firewall render`.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Generated from policy version %s. Do not edit by hand: the next render\n", p.Version)
	fmt.Fprintf(b, "# will overwrite this file, and any local edit will be lost.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   policy:  %s\n", p)
	fmt.Fprintf(b, "#   family:  %s\n", p.Family)
	fmt.Fprintf(b, "#   table:   %s\n", p.Table)
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# To inspect the running ruleset:   nft list table %s %s\n", p.Family, p.Table)
	fmt.Fprintf(b, "# To load this file:               nft -f <this-file>\n")
	fmt.Fprintf(b, "#\n")

	for _, c := range p.Comments {
		for _, line := range strings.Split(c, "\n") {
			fmt.Fprintf(b, "# %s\n", line)
		}
	}
	if len(p.Comments) > 0 {
		fmt.Fprintf(b, "#\n")
	}
}

// writeTable emits the table and its base chains.
func writeTable(b *strings.Builder, p policy.Policy) {
	fmt.Fprintf(b, "table %s %s {\n", p.Family, p.Table)

	fmt.Fprintf(b, "\n")
	writeComment(b, "Named chain for rules that do not terminate evaluation, so the")
	writeComment(b, "default policy remains the final decision.")
	fmt.Fprintf(b, "\tchain forward_chain {\n")
	fmt.Fprintf(b, "\t}\n")

	fmt.Fprintf(b, "\n")
	writeComment(b, "Named chain for port-based access. Reached from the input hook.")
	fmt.Fprintf(b, "\tchain services {\n")
	fmt.Fprintf(b, "\t}\n\n")
}

// writeInputChain emits the input hook, where administrative access lives.
func writeInputChain(b *strings.Builder, p policy.Policy) {
	fmt.Fprintf(b, "\tchain input {\n")
	fmt.Fprintf(b, "\t\ttype filter hook input priority filter; policy %s\n", "drop")
	fmt.Fprintf(b, "\n")

	writeComment(b, "Return traffic for anything already permitted. This must come")
	writeComment(b, "first: without it, reply packets to new connections would be")
	writeComment(b, "dropped by the default policy above.")
	writeRule(b, p, "\t\t", "ct state established,related accept", "allow return traffic")

	lo := p.Interfaces.Loopback
	if lo == "" {
		lo = "lo"
	}
	writeRule(b, p, "\t\t",
		fmt.Sprintf("iifname %q accept", lo),
		"local traffic never traverses an external interface")

	writeRule(b, p, "\t\t",
		"iifname \"tailscale0\" accept",
		"preserve Tailscale remote management path")
	writeRule(b, p, "\t\t",
		"udp dport 41641 accept",
		"preserve Tailscale WireGuard peering")

	if p.Interfaces.LAN != "" {
		if p.ICMP.AllowLAN {
			writeRule(b, p, "\t\t",
				fmt.Sprintf("iifname %q icmp accept", p.Interfaces.LAN),
				"LAN clients may reach this host")
		}
		writeRule(b, p, "\t\t",
			fmt.Sprintf("iifname %q tcp dport { 80, 1717, 8080 } accept", p.Interfaces.LAN),
			"LAN management web console access")
		writeRule(b, p, "\t\t",
			fmt.Sprintf("iifname %q udp dport { 53, 67 } accept", p.Interfaces.LAN),
			"LAN DNS and DHCP queries")
		writeRule(b, p, "\t\t",
			fmt.Sprintf("iifname %q tcp dport 53 accept", p.Interfaces.LAN),
			"LAN DNS TCP queries")
	}

	if p.ICMP.AllowWAN {
		writeICMPInput(b, p)
	}

	// Services, admin first. The renderer emits the admin service ahead of any
	// added service so that a later rule can never shadow the admin path.
	if p.Admin.Enabled && renderableService(p.Admin.Service) {
		writeComment(b, "Administration access. The ruleset is unusable without this;")
		writeComment(b, "check `thn firewall render` validation before removing it.")
		writeService(b, p, p.Admin.Service, p.Admin.Source, true)

		if len(p.Admin.Source) == 0 {
			writeComment(b, "No source restriction is configured: this rule accepts")
			writeComment(b, "administration traffic from any address.")
		} else {
			writeComment(b, "Administration is restricted to the source networks above.")
		}
	}

	for _, s := range p.Services {
		if !renderableService(s) {
			continue
		}
		writeService(b, p, s, s.Source, false)
	}

	fmt.Fprintf(b, "\n")
	writeComment(b, "Anything not explicitly permitted above is dropped. A host that")
	writeComment(b, "forwards traffic does not need to answer on the WAN.")
	fmt.Fprintf(b, "\t}\n\n")
}

// writeICMPInput emits ICMP handling for the input hook.
func writeICMPInput(b *strings.Builder, p policy.Policy) {
	writeComment(b, "ICMP is permitted rather than dropped: it carries path MTU discovery,")
	writeComment(b, "and a gateway that blocks it causes traffic to black hole silently")
	writeComment(b, "rather than fail visibly.")

	wan := p.Interfaces.WAN
	if wan == "" {
		// Without a WAN interface the rule would be meaningless, so ICMP is
		// permitted on all interfaces and a comment records why.
		writeComment(b, "No WAN interface is configured, so ICMP is permitted generally.")
		writeRule(b, p, "\t\t", "icmp type echo-request limit rate 10/second accept",
			"ICMP echo, rate limited against amplification abuse")
		return
	}

	if p.ICMP.RateLimitEcho > 0 {
		writeRule(b, p, "\t\t",
			fmt.Sprintf("iifname %q icmp type echo-request limit rate %d/second accept",
				wan, p.ICMP.RateLimitEcho),
			"ICMP echo to this host, rate limited against amplification abuse")
	} else {
		writeRule(b, p, "\t\t",
			fmt.Sprintf("iifname %q icmp type echo-request accept", wan),
			"ICMP echo to this host")
	}

	writeRule(b, p, "\t\t",
		fmt.Sprintf("iifname %q icmp type destination-unreachable accept", wan),
		"path MTU discovery: required for correct behaviour of long packets")
	writeRule(b, p, "\t\t",
		fmt.Sprintf("iifname %q icmp type time-exceeded accept", wan),
		"traceroute uses this; without it hops appear as timeouts rather than replies")
}

// writeForwardChain emits the forward hook.
func writeForwardChain(b *strings.Builder, p policy.Policy) {
	fmt.Fprintf(b, "\tchain forward {\n")
	fmt.Fprintf(b, "\t\ttype filter hook forward priority filter; policy %s\n", "drop")
	fmt.Fprintf(b, "\n")

	writeRule(b, p, "\t\t", "ct state established,related accept",
		"allow return traffic for connections already permitted")

	if p.Forward.RejectInvalid {
		writeRule(b, p, "\t\t", "ct state invalid drop",
			"drop packets that fail connection tracking; they are usually spoofed or out of sequence")
	}

	if p.AntiSpoofing.Enabled && p.AntiSpoofing.LANPrefix != "" {
		wan := p.Interfaces.WAN
		if wan == "" {
			writeComment(b, "Anti-spoofing needs a WAN interface to be meaningful and has")
			writeComment(b, "been skipped because none is configured.")
		} else {
			writeRule(b, p, "\t\t",
				fmt.Sprintf("iifname %q ip saddr %s drop", wan, p.AntiSpoofing.LANPrefix),
				"a packet claiming a LAN source address but arriving on the WAN is spoofed")
		}
	}

	lan, wan := p.Interfaces.LAN, p.Interfaces.WAN

	if p.Forward.LANToLAN {
		writeRule(b, p, "\t\t", "iifname forward_chain oifname forward_chain accept",
			"permit traffic between LAN interfaces")
	}

	if p.Forward.LANToWAN {
		if lan != "" && wan != "" {
			writeRule(b, p, "\t\t",
				fmt.Sprintf("iifname %q oifname %q accept", lan, wan),
				"the purpose of a gateway: LAN clients reaching the internet")
		} else {
			writeComment(b, "LAN-to-WAN forwarding is enabled but cannot be expressed because")
			writeComment(b, "one of the interfaces is unidentified. Traffic will be dropped")
			writeComment(b, "until both are configured.")
			writeComment(b, "")
			writeComment(b, "    intended: iifname \"lan\" oifname \"wan\" accept")
		}
	} else {
		writeComment(b, "LAN-to-WAN forwarding is disabled by policy. The LAN will have")
		writeComment(b, "no internet access.")
	}

	if p.Forward.WANToLAN {
		if wan != "" && lan != "" {
			writeRule(b, p, "\t\t",
				fmt.Sprintf("iifname %q oifname %q accept", wan, lan),
				"UNSOLICITED INBOUND TRAFFIC: every device on the LAN is exposed")
		} else {
			writeComment(b, "WAN-to-LAN forwarding is enabled but cannot be expressed because")
			writeComment(b, "one of the interfaces is unidentified.")
			writeComment(b, "")
			writeComment(b, "    intended: iifname \"wan\" oifname \"lan\" accept")
		}
	}

	if p.ICMP.AllowForward {
		writeComment(b, "ICMP across the gateway. PMTU discovery depends on this; blocking")
		writeComment(b, "it stalls traffic silently rather than failing it.")
		writeRule(b, p, "\t\t", "icmp accept", "permit ICMP between the LAN and the WAN")
	}

	fmt.Fprintf(b, "\n")
	writeComment(b, "Traffic not permitted above is dropped.")
	fmt.Fprintf(b, "\t}\n\n")
}

// writeNatChain emits the prerouting chain used for port forwarding.
//
// THN generates no inbound port forwards: the WAN-to-LAN direction is denied
// by policy, so there is nothing to forward. The chain exists because nftables
// requires it for any nat table declaration, and an empty one documents the
// intent explicitly.
//
// The hook declaration must be emitted before the explanatory comments. A
// comment line between "chain prerouting {" and its hook line would leave the
// chain with no hook, which nft accepts silently and which then quietly drops
// every prerouted packet.
func writeNatChain(b *strings.Builder, p policy.Policy) {
	fmt.Fprintf(b, "\tchain prerouting {\n")
	fmt.Fprintf(b, "\t\ttype nat hook prerouting priority dstnat; policy accept\n")
	fmt.Fprintf(b, "\n")
	if p.Interfaces.LAN != "" {
		writeComment(b, "Redirect HTTP (port 80) from LAN to management console port 1717")
		writeRule(b, p, "\t\t",
			fmt.Sprintf("iifname %q tcp dport 80 redirect to :1717", p.Interfaces.LAN),
			"router-style web console access on 10.77.0.1")
	}
	writeComment(b, "No inbound port forwards are generated. The policy denies")
	writeComment(b, "unsolicited WAN-to-LAN traffic, so there is nothing to")
	writeComment(b, "forward; add a rule here only alongside a matching")
	writeComment(b, "forward-chain accept.")
	fmt.Fprintf(b, "\t}\n\n")
}

// writePostrouting emits source NAT.
func writePostrouting(b *strings.Builder, p policy.Policy) {
	fmt.Fprintf(b, "\tchain postrouting {\n")
	fmt.Fprintf(b, "\t\ttype nat hook postrouting priority srcnat; policy accept\n")
	fmt.Fprintf(b, "\n")

	if !p.Masquerade.Enabled {
		writeComment(b, "Masquerading is disabled by policy. LAN traffic will leave with")
		writeComment(b, "its original source address, which most upstream networks will drop.")
		fmt.Fprintf(b, "\t}\n\n")
		return
	}

	writeComment(b, "Source NAT for traffic leaving the WAN. Without this the upstream")
	writeComment(b, "sees unroutable source addresses and drops the return traffic.")

	switch {
	case p.Masquerade.OutInterface != "":
		writeRule(b, p, "\t\t",
			fmt.Sprintf("oifname %q masquerade", p.Masquerade.OutInterface),
			"masquerade traffic leaving the WAN")

	case p.Interfaces.WAN != "":
		writeRule(b, p, "\t\t",
			fmt.Sprintf("oifname %q masquerade", p.Interfaces.WAN),
			"masquerade traffic leaving the WAN")

	default:
		writeComment(b, "No WAN interface is configured, so masquerading cannot be scoped to")
		writeComment(b, "an outbound interface. It is deliberately NOT emitted: an")
		writeComment(b, "unscoped masquerade rule would rewrite traffic leaving every")
		writeComment(b, "interface, including the LAN.")
		writeComment(b, "")
		writeComment(b, "    intended: oifname \"wan\" masquerade")
	}

	fmt.Fprintf(b, "\t}\n\n")
}

// writeLogging emits the log table when logging is enabled.
func writeLogging(b *strings.Builder, p policy.Policy) {
	if !p.Logging.Enabled {
		return
	}

	limit := p.Logging.LogLimit
	if limit <= 0 {
		limit = 1000
	}
	rate := p.Logging.RateLimit

	fmt.Fprintf(b, "\n")
	writeComment(b, "Rule matches are recorded in a separate table so that the filter")
	writeComment(b, "tables stay readable when a rule is hit often.")

	if rate > 0 {
		writeRule(b, p, "\t", fmt.Sprintf("limit rate %d/second", rate),
			"unlimited logging on a busy link fills a disk")
	} else {
		writeComment(b, "No rate limit is configured; on a busy link this will fill a disk.")
	}

	fmt.Fprintf(b, "\tlog prefix \"thn-drop \" limit log-prefix \"thn-drop-\" %d\n", limit)
}

// writeService emits one service's accept rule.
//
// The admin service carries its source restriction in Policy.Admin.Source
// rather than in Service.Source, because administration is a separate concept
// with its own gate. Callers must therefore pass the restriction explicitly:
// reading only Service.Source would silently drop it and render an admin rule
// that accepts from anywhere, which is the opposite of what was configured.
func writeService(b *strings.Builder, p policy.Policy, s policy.Service, source []string, isAdmin bool) {
	if s.Comment != "" {
		writeComment(b, s.Comment)
	}

	ind := "\t\t"
	if !isAdmin {
		ind = "\t\t\t"
	}

	proto := nftProtocol(s.Protocol)
	sources := renderSources(source)

	ports := make([]string, len(s.Ports))
	for i, pr := range s.Ports {
		ports[i] = pr.String()
	}
	portSpec := strings.Join(ports, ", ")

	expr := fmt.Sprintf("meta l4proto %s", proto)
	if len(s.Ports) > 0 && proto != "icmp" && proto != "icmpv6" {
		if s.Protocol == policy.ProtoAll {
			expr = fmt.Sprintf("th dport { %s }", portSpec)
		} else {
			expr = fmt.Sprintf("%s dport { %s }", proto, portSpec)
		}
	}

	if sources != "" {
		expr = fmt.Sprintf("%s %s", sources, expr)
	}

	writeRule(b, p, ind, expr+" accept",
		fmt.Sprintf("permit %s from the WAN", s.Name))
}

// renderSources renders a source restriction clause.
func renderSources(src []string) string {
	if len(src) == 0 {
		return ""
	}

	prefixes := append([]string(nil), src...)
	sort.Strings(prefixes)

	v6 := false
	for _, p := range prefixes {
		if strings.Contains(p, ":") {
			v6 = true
		}
	}

	expr := fmt.Sprintf("ip saddr { %s }", strings.Join(prefixes, ", "))
	if v6 {
		// A mixed family list needs both matchers; the ipv6 one is emitted
		// alongside rather than instead, and nft accepts the conjunction.
		v6Only := make([]string, 0, len(prefixes))
		for _, p := range prefixes {
			if strings.Contains(p, ":") {
				v6Only = append(v6Only, p)
			}
		}
		expr = fmt.Sprintf("ip saddr { %s }", strings.Join(prefixes, ", "))
		if len(v6Only) > 0 {
			expr = fmt.Sprintf("(ip saddr { %s } or ip6 saddr { %s })",
				strings.Join(nonV6(prefixes), ", "), strings.Join(v6Only, ", "))
		}
	}
	return expr
}

// nonV6 returns the IPv4 members of a prefix list.
func nonV6(prefixes []string) []string {
	out := make([]string, 0, len(prefixes))
	for _, p := range prefixes {
		if !strings.Contains(p, ":") {
			out = append(out, p)
		}
	}
	return out
}

// nftProtocol maps a THN protocol onto its nftables name.
func nftProtocol(p policy.Protocol) string {
	switch p {
	case policy.ProtoTCP:
		return "tcp"
	case policy.ProtoUDP:
		return "udp"
	case policy.ProtoICMP:
		return "icmp"
	case policy.ProtoICMPv6:
		return "icmpv6"
	case policy.ProtoESP:
		return "esp"
	case policy.ProtoAH:
		return "ah"
	default:
		return "ip"
	}
}

// renderableService reports whether a service can produce a valid rule.
func renderableService(s policy.Service) bool {
	return s.Name != "" && s.Protocol.Valid() && len(s.Ports) > 0
}

// writeRule emits one rule with a trailing comment.
//
// The comment is appended as an nft comment rather than an nft "#" line,
// because nft strips "#" lines when loading and the comment is most useful
// when someone lists the live ruleset.
func writeRule(b *strings.Builder, p policy.Policy, indent, expr, comment string) {
	if comment == "" {
		fmt.Fprintf(b, "%s%s\n", indent, expr)
		return
	}
	fmt.Fprintf(b, "%s%s comment \"%s\"\n", indent, expr, escapeComment(comment))
}

// writeComment emits a comment line.
//
// Comments use the chain body indent rather than the indent passed to
// writeRule. Rule bodies vary by chain, but a comment always belongs to the
// chain it sits in, so anchoring comments to the chain keeps the generated
// file readable instead of staircased.
func writeComment(b *strings.Builder, text string) {
	for _, line := range strings.Split(text, "\n") {
		if line == "" {
			fmt.Fprintf(b, "\t\t#\n")
			continue
		}
		fmt.Fprintf(b, "\t\t# %s\n", line)
	}
}

// escapeComment makes a string safe inside an nft double-quoted comment.
//
// A comment containing a quote or a backslash would otherwise produce a
// ruleset that fails to parse — and a ruleset that fails to parse is a
// firewall that was never loaded.
func escapeComment(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return strings.ReplaceAll(s, "\n", " ")
}
