package tc

import (
	"fmt"
	"strings"

	"github.com/venth/thn-gateway/internal/qos"
)

// Render produces the traffic-shaping commands for a policy.
//
// The output is a shell script for review. It is not run: this package
// imports no os/exec, so there is no path from here to applying a command.
// That is the same guarantee the rest of THN gives, and the guard test
// enforces it repository-wide.
func Render(p qos.Policy, sel qos.Selection) string {
	p.Algorithm = sel.Algorithm

	var b strings.Builder

	writeHeader(&b, p, sel)
	writeApply(&b, p, sel)
	writeVerification(&b, p)
	writeRemoval(&b, p)
	writeNotes(&b, p, sel)

	return b.String()
}

// writeHeader emits the preamble and the degradation notice.
func writeHeader(b *strings.Builder, p qos.Policy, sel qos.Selection) {
	fmt.Fprintf(b, "#!/bin/sh\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# THN traffic shaping, generated by `thn qos render`.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Generated. Do not edit by hand: the next render replaces it.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   %s\n", p)
	fmt.Fprintf(b, "#\n")

	if sel.Degraded {
		fmt.Fprintf(b, "# ── DEGRADED ────────────────────────────────────────────────\n")
		fmt.Fprintf(b, "#\n")
		fmt.Fprintf(b, "# Requested: %s.  Available: %s.\n", sel.Requested, sel.Algorithm)
		fmt.Fprintf(b, "#\n")
		fmt.Fprintf(b, "# %s\n", sel.Reason)
		fmt.Fprintf(b, "#\n")
		fmt.Fprintf(b, "# What this means: %s smooths bursts and keeps the device's\n", sel.Algorithm)
		fmt.Fprintf(b, "# own queue short, but it has no knowledge of the link's rate and\n")
		fmt.Fprintf(b, "# therefore cannot shape. The bottleneck queue further up will\n")
		fmt.Fprintf(b, "# still fill, and latency under load will still spike.\n")
		fmt.Fprintf(b, "#\n")
		fmt.Fprintf(b, "# To get the intended behaviour, run on a kernel with %s:\n", sel.Requested)
		fmt.Fprintf(b, "#   modprobe sch_cake\n")
		fmt.Fprintf(b, "#\n")
	}

	fmt.Fprintf(b, "# THN does not apply this. After reviewing it:\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   sh -n <this-file>     # syntax check only\n")
	fmt.Fprintf(b, "#   sh <this-file>\n")
	fmt.Fprintf(b, "#\n")

	for _, c := range p.Comments {
		for _, line := range strings.Split(c, "\n") {
			fmt.Fprintf(b, "# %s\n", line)
		}
	}
	if len(p.Comments) > 0 {
		fmt.Fprintf(b, "#\n")
	}
}

// writeApply emits the command that installs the qdisc.
func writeApply(b *strings.Builder, p qos.Policy, sel qos.Selection) {
	fmt.Fprintf(b, "# --- apply --------------------------------------------------------\n")
	fmt.Fprintf(b, "#\n")

	iface := p.Interface
	if iface == "" {
		fmt.Fprintf(b, "# No interface is configured, so no command can be generated.\n")
		fmt.Fprintf(b, "\n")
		return
	}

	switch sel.Algorithm {
	case qos.AlgorithmCake:
		writeCake(b, p, iface)
	case qos.AlgorithmFqCodel:
		writeFqCodel(b, p, iface)
	case qos.AlgorithmNone:
		fmt.Fprintf(b, "# The algorithm is \"none\"; no shaping will be applied.\n\n")
	default:
		fmt.Fprintf(b, "# No usable algorithm; no command can be generated.\n\n")
	}
}

// writeCake emits the CAKE command.
//
// CAKE's bandwidth is the wire rate, not the payload rate, so the configured
// figures are raised by the overhead allowance before being passed. Shaping at
// exactly the provisioned payload rate would leave the link permanently
// under-utilised by about a tenth.
func writeCake(b *strings.Builder, p qos.Policy, iface string) {
	down := p.Bandwidth.Effective(qos.Download)
	up := p.Bandwidth.Effective(qos.Upload)

	fmt.Fprintf(b, "# CAKE is rate-aware: it shapes toward the configured bandwidth and\n")
	fmt.Fprintf(b, "# keeps this device's queue short, which is what reduces bufferbloat.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# The rates below include %d%% framing overhead, so the payload rate\n",
		overheadPercent(p))
	fmt.Fprintf(b, "# reaches the configured %dkbit/s down and %dkbit/s up.\n",
		p.Bandwidth.DownloadKbps, p.Bandwidth.UploadKbps)
	fmt.Fprintf(b, "\n")

	var args []string
	args = append(args, "tc qdisc replace dev "+iface+" root cake")

	if down > 0 {
		args = append(args, "bandwidth", fmt.Sprintf("%dkbit", down))
	}
	if up > 0 {
		args = append(args, "uplink", fmt.Sprintf("%dkbit", up))
	}

	args = append(args, "target", fmt.Sprintf("%dms", p.Limits.TargetMS))
	args = append(args, "interval", fmt.Sprintf("%dms", p.Limits.IntervalMS))
	if p.Limits.Quantum > 0 {
		args = append(args, "quantum", fmt.Sprintf("%d", p.Limits.Quantum))
	}

	// besteffort distributes bandwidth by flow rather than per-packet, which
	// is what stops one bulk transfer from starving interactive traffic.
	args = append(args, "besteffort")

	// diffserv4 honours the DSCP markings that interactive traffic already
	// carries, so a marked packet is not delayed behind an unmarked one.
	args = append(args, "diffserv4")

	fmt.Fprintf(b, "%s\n", strings.Join(args, " "))
	fmt.Fprintf(b, "\n")
}

// writeFqCodel emits the fq_codel command and states its limitation.
//
// fq_codel has no rate parameters. That is not an oversight in the rendering:
// it is the reason the fallback is reported as a degradation.
func writeFqCodel(b *strings.Builder, p qos.Policy, iface string) {
	quantum := p.Limits.Quantum
	if quantum <= 0 {
		quantum = p.MTU
	}
	if quantum <= 0 {
		quantum = 1500
	}

	fmt.Fprintf(b, "# fq_codel has no rate parameters and cannot enforce a bandwidth.\n")
	fmt.Fprintf(b, "# It separates flows and controls the queue delay, which reduces\n")
	fmt.Fprintf(b, "# jitter on this device, but the bottleneck queue upstream still\n")
	fmt.Fprintf(b, "# fills under load. The configured %dkbit/s down and %dkbit/s up\n",
		p.Bandwidth.DownloadKbps, p.Bandwidth.UploadKbps)
	fmt.Fprintf(b, "# rates are NOT applied.\n")
	fmt.Fprintf(b, "\n")

	fmt.Fprintf(b, "# limit    %s   queue depth in packets\n", "10240")
	fmt.Fprintf(b, "# flows    %s   number of per-flow queues\n", "1024")
	fmt.Fprintf(b, "# quantum  %s   bytes per round, should match the MTU\n\n", fmt.Sprintf("%d", quantum))

	args := []string{
		"tc qdisc replace dev " + iface + " root fq_codel",
		"limit 10240",
		"flows 1024",
		fmt.Sprintf("quantum %d", quantum),
	}
	fmt.Fprintf(b, "%s\n", strings.Join(args, " "))
	fmt.Fprintf(b, "\n")
}

// overheadPercent renders the configured overhead allowance.
func overheadPercent(p qos.Policy) int {
	if p.Bandwidth.OverheadPercent == 0 {
		return qos.DefaultOverheadPercent
	}
	return p.Bandwidth.OverheadPercent
}

// writeVerification emits the read-only commands an operator should run after
// applying, so they can confirm the result rather than assume it.
func writeVerification(b *strings.Builder, p qos.Policy) {
	if p.Interface == "" {
		return
	}

	fmt.Fprintf(b, "# --- verify ------------------------------------------------------\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Read-only. Run these after applying to confirm the result.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "#   tc -s qdisc show dev %s\n", p.Interface)
	fmt.Fprintf(b, "#   thn qos stats --interface %s\n", p.Interface)
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# A healthy shaper shows a high overlimit count and a low drop\n")
	fmt.Fprintf(b, "# count under load. The reverse means the shaped rate is below the\n")
	fmt.Fprintf(b, "# offered load.\n")
	fmt.Fprintf(b, "\n")
}

// writeRemoval emits the teardown command.
func writeRemoval(b *strings.Builder, p qos.Policy) {
	if p.Interface == "" {
		return
	}

	fmt.Fprintf(b, "# --- remove ------------------------------------------------------\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Replaces the root qdisc with pfifo_fast, which is the kernel default.\n")
	fmt.Fprintf(b, "# Undoing this removes all shaping, so bufferbloat returns.\n")
	fmt.Fprintf(b, "\n")
	fmt.Fprintf(b, "# tc qdisc replace dev %s root pfifo_fast\n\n", p.Interface)
}

// writeNotes emits the closing reminders.
func writeNotes(b *strings.Builder, p qos.Policy, sel qos.Selection) {
	fmt.Fprintf(b, "# --- before applying ----------------------------------------------\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Applying this changes host networking. From a remote session, a\n")
	fmt.Fprintf(b, "# mistyped interface name removes shaping on the wrong link, or a\n")
	fmt.Fprintf(b, "# wrong rate throttles the connection.\n")
	fmt.Fprintf(b, "#\n")
	fmt.Fprintf(b, "# Capture the current state first:\n")
	fmt.Fprintf(b, "#   tc -s qdisc show > /tmp/qdisc-before.txt\n")
	fmt.Fprintf(b, "#\n")

	if p.Bandwidth.IsZero() {
		fmt.Fprintf(b, "# NOTE: no bandwidth is configured. Without one, CAKE has nothing\n")
		fmt.Fprintf(b, "# to shape toward and the rules below would be meaningless.\n")
		fmt.Fprintf(b, "\n")
	}

	if sel.Degraded {
		fmt.Fprintf(b, "# REMINDER: this build will not reduce bufferbloat. See the notice\n")
		fmt.Fprintf(b, "# at the top of this file.\n")
		fmt.Fprintf(b, "\n")
	}
}
